In [12]:

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.metrics import r2_score, mean_squared_error

pd.set_option('display.max_columns', 70)
pd.set_option('display.max_rows', 13)

In [15]:
# The code was removed by Watson Studio for sharing.

/opt/conda/envs/Python36/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3020: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,CRASH DATE,CRASH TIME,BOROUGH,ZIP CODE,LATITUDE,LONGITUDE,LOCATION,ON STREET NAME,CROSS STREET NAME,OFF STREET NAME,NUMBER OF PERSONS INJURED,NUMBER OF PERSONS KILLED,NUMBER OF PEDESTRIANS INJURED,NUMBER OF PEDESTRIANS KILLED,NUMBER OF CYCLIST INJURED,NUMBER OF CYCLIST KILLED,NUMBER OF MOTORIST INJURED,NUMBER OF MOTORIST KILLED,CONTRIBUTING FACTOR VEHICLE 1,CONTRIBUTING FACTOR VEHICLE 2,CONTRIBUTING FACTOR VEHICLE 3,CONTRIBUTING FACTOR VEHICLE 4,CONTRIBUTING FACTOR VEHICLE 5,COLLISION_ID,VEHICLE TYPE CODE 1,VEHICLE TYPE CODE 2,VEHICLE TYPE CODE 3,VEHICLE TYPE CODE 4,VEHICLE TYPE CODE 5
0,09/13/2020,13:20,QUEENS,11004,0.000000,0.000000,"(0.0, 0.0)",NaN,NaN,81-23 262 STREET,0.0,0.0,0,0,0,0,0,0,Unspecified,NaN,NaN,NaN,NaN,4347343,NaN,NaN,NaN,NaN,NaN
1,09/12/2020,18:23,NaN,NaN,NaN,NaN,NaN,102 CROSS DRIVE,EAST DRIVE,NaN,2.0,0.0,1,0,1,0,0,0,Driver Inexperience,NaN,NaN,NaN,NaN,4347479,Bike,NaN,NaN,NaN,NaN
2,09/12/2020,22:00,NaN,NaN,40.819378,-73.960350,"(40.819378, -73.96035)",HENRY HUDSON PARKWAY,NaN,NaN,0.0,0.0,0,0,0,0,0,0,Unspecified,NaN,NaN,NaN,NaN,4347290,Sedan,NaN,NaN,NaN,NaN
3,09/11/2020,0:16,BRONX,10463,40.879555,-73.904335,"(40.879555, -73.904335)",NaN,NaN,5600 BROADWAY,0.0,0.0,0,0,0,0,0,0,Driver Inattention/Distraction,NaN,NaN,NaN,NaN,4346740,Sedan,NaN,NaN,NaN,NaN
4,09/10/2020,10:26,BRONX,10455,40.818157,-73.906250,"(40.818157, -73.90625)",FOREST AVENUE,EAST 156 STREET,NaN,0.0,0.0,0,0,0,0,0,0,Unspecified,Unspecified,NaN,NaN,NaN,4346697,Sedan,Sedan,NaN,NaN,NaN

In [19]:
df_data_1.head(10)

,CRASH DATE,CRASH TIME,BOROUGH,ZIP CODE,LATITUDE,LONGITUDE,LOCATION,ON STREET NAME,CROSS STREET NAME,OFF STREET NAME,NUMBER OF PERSONS INJURED,NUMBER OF PERSONS KILLED,NUMBER OF PEDESTRIANS INJURED,NUMBER OF PEDESTRIANS KILLED,NUMBER OF CYCLIST INJURED,NUMBER OF CYCLIST KILLED,NUMBER OF MOTORIST INJURED,NUMBER OF MOTORIST KILLED,CONTRIBUTING FACTOR VEHICLE 1,CONTRIBUTING FACTOR VEHICLE 2,CONTRIBUTING FACTOR VEHICLE 3,CONTRIBUTING FACTOR VEHICLE 4,CONTRIBUTING FACTOR VEHICLE 5,COLLISION_ID,VEHICLE TYPE CODE 1,VEHICLE TYPE CODE 2,VEHICLE TYPE CODE 3,VEHICLE TYPE CODE 4,VEHICLE TYPE CODE 5
0,09/13/2020,13:20,QUEENS,11004,0.000000,0.000000,"(0.0, 0.0)",NaN,NaN,81-23 262 STREET,0.0,0.0,0,0,0,0,0,0,Unspecified,NaN,NaN,NaN,NaN,4347343,NaN,NaN,NaN,NaN,NaN
1,09/12/2020,18:23,NaN,NaN,NaN,NaN,NaN,102 CROSS DRIVE,EAST DRIVE,NaN,2.0,0.0,1,0,1,0,0,0,Driver Inexperience,NaN,NaN,NaN,NaN,4347479,Bike,NaN,NaN,NaN,NaN
2,09/12/2020,22:00,NaN,NaN,40.819378,-73.960350,"(40.819378, -73.96035)",HENRY HUDSON PARKWAY,NaN,NaN,0.0,0.0,0,0,0,0,0,0,Unspecified,NaN,NaN,NaN,NaN,4347290,Sedan,NaN,NaN,NaN,NaN
3,09/11/2020,0:16,BRONX,10463,40.879555,-73.904335,"(40.879555, -73.904335)",NaN,NaN,5600 BROADWAY,0.0,0.0,0,0,0,0,0,0,Driver Inattention/Distraction,NaN,NaN,NaN,NaN,4346740,Sedan,NaN,NaN,NaN,NaN
4,09/10/2020,10:26,BRONX,10455,40.818157,-73.906250,"(40.818157, -73.90625)",FOREST AVENUE,EAST 156 STREET,NaN,0.0,0.0,0,0,0,0,0,0,Unspecified,Unspecified,NaN,NaN,NaN,4346697,Sedan,Sedan,NaN,NaN,NaN
5,09/10/2020,13:10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,WASHINGTON AVENUE,0.0,0.0,0,0,0,0,0,0,Turning Improperly,Unspecified,NaN,NaN,NaN,4346836,Leased amb,Sedan,NaN,NaN,NaN
6,09/09/2020,12:00,NaN,NaN,40.600690,-74.010056,"(40.60069, -74.010056)",BELT PARKWAY,NaN,NaN,0.0,0.0,0,0,0,0,0,0,Reaction to Uninvolved Vehicle,NaN,NaN,NaN,NaN,4347147,Sedan,NaN,NaN,NaN,NaN
7,09/08/2020,11:30,NaN,NaN,40.800964,-73.971016,"(40.800964, -73.971016)",WEST 104 STREET,NaN,NaN,0.0,0.0,0,0,0,0,0,0,Unspecified,NaN,NaN,NaN,NaN,4346464,Sedan,NaN,NaN,NaN,NaN
8,09/07/2020,0:41,NaN,NaN,40.738503,-73.973526,"(40.738503, -73.973526)",FDR DRIVE,NaN,NaN,0.0,0.0,0,0,0,0,0,0,Unspecified,NaN,NaN,NaN,NaN,4345579,Motorcycle,Sedan,NaN,NaN,NaN
9,09/07/2020,14:45,NaN,NaN,NaN,NaN,NaN,VERRAZANO BRIDGE LOWER,NaN,NaN,0.0,0.0,0,0,0,0,0,0,Unspecified,Unspecified,Unspecified,Unspecified,NaN,4346058,Sedan,Sedan,Sedan,Sedan,NaN

In [20]:
df_data_1.isnull().sum().sum()

14569502

In [21]:
df_data_1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1711577 entries, 0 to 1711576
Data columns (total 29 columns):
CRASH DATE                       object
CRASH TIME                       object
BOROUGH                          object
ZIP CODE                         object
LATITUDE                         float64
LONGITUDE                        float64
LOCATION                         object
ON STREET NAME                   object
CROSS STREET NAME                object
OFF STREET NAME                  object
NUMBER OF PERSONS INJURED        float64
NUMBER OF PERSONS KILLED         float64
NUMBER OF PEDESTRIANS INJURED    int64
NUMBER OF PEDESTRIANS KILLED     int64
NUMBER OF CYCLIST INJURED        int64
NUMBER OF CYCLIST KILLED         int64
NUMBER OF MOTORIST INJURED       int64
NUMBER OF MOTORIST KILLED        int64
CONTRIBUTING FACTOR VEHICLE 1    object
CONTRIBUTING FACTOR VEHICLE 2    object
CONTRIBUTING FACTOR VEHICLE 3    object
CONTRIBUTING FACTOR VEHICLE 4    object
CONTRIBUTING FACTOR VEHICLE 5    object
COLLISION_ID                     int64
VEHICLE TYPE CODE 1              object
VEHICLE TYPE CODE 2              object
VEHICLE TYPE CODE 3              object
VEHICLE TYPE CODE 4              object
VEHICLE TYPE CODE 5              object
dtypes: float64(4), int64(7), object(18)
memory usage: 378.7+ MB

In [28]:
df_data_1 = df_data_1['NUMBER OF PERSONS INJURED'].fillna(0)

In [40]:
df_data_1.info()

AttributeError: 'Series' object has no attribute 'info'